{{- if not .Values.database.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "domain-in-a-box.fullname" . }}-postgresql
  labels:
    {{- include "domain-in-a-box.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  selector:
    {{- include "domain-in-a-box.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "domain-in-a-box.fullname" . }}-postgresql
  labels:
    {{- include "domain-in-a-box.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "domain-in-a-box.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      {{- include "domain-in-a-box.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "domain-in-a-box.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:18-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: "stork"
            - name: POSTGRES_USER
              value: "stork"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "domain-in-a-box.fullname" . }}-secret
                  key: stork-db-password
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: 5Gi
{{- end }}
