apiVersion: v1
kind: Secret
metadata:
  name: {{ include "domain-in-a-box.fullname" . }}-secret
  labels:
    {{- include "domain-in-a-box.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.domain.adminPasswordSecret.name }}
  domain-admin-password: {{ .Values.domain.initialAdminPassword | quote }}
  {{- end }}
  stork-db-password: {{ .Values.database.initialPassword | default "storkpass123!" | quote }}
  stork-ldap-password: {{ .Values.database.initialLDAPPassword | default "ChangeMeLDAP123!" | quote }}
