apiVersion: v2
name: domain-in-a-box
description: A Helm chart for Domain-In-A-Box (Active Directory DC, BIND9, Kea DHCP, Chrony, Stork)
type: application
version: 0.2.0
appVersion: "0.3.5"
keywords:
  - active-directory
  - dns
  - dhcp
  - ntp
  - samba
  - bind9
  - kea
  - stork
maintainers:
  - name: GMouzourou
