[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
childlogdir=/var/log

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:chrony]
command=/usr/sbin/chronyd -n -x -f /etc/chrony/chrony.conf
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:samba]
command=/usr/sbin/samba -i
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2

[program:bind]
command=/usr/sbin/named -f -c /etc/bind/named.conf
user=bind
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=3

[program:cron]
command=/usr/sbin/cron -f -L 15
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=4

[program:postgresql]
command=/bin/sh /entrypoint.d/postgres.sh run
user=postgres
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

[program:init]
command=/bin/sh /entrypoint.d/init.sh
user=root
exitcodes=0
autorestart=false
startretries=1
environment=INIT_DOMAIN="%(ENV_INIT_DOMAIN)s",DNS_DOMAIN="%(ENV_DNS_DOMAIN)s",CONTAINER_HOSTNAME="%(ENV_CONTAINER_HOSTNAME)s",IP="%(ENV_IP)s",SUBNET="%(ENV_SUBNET)s",REVERSE_ZONE="%(ENV_REVERSE_ZONE)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=6

[program:kea-dhcp4]
command=/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf
user=_kea
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=7

[program:kea-dhcp-ddns]
command=/usr/sbin/kea-dhcp-ddns -c /etc/kea/kea-dhcp-ddns.conf
user=_kea
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=8

[program:smb-prometheus-endpoint]
command=/bin/bash -c "if [ \"%(ENV_DIB_SAMBA_METRICS_ENABLED)s\" = \"on\" ]; then sleep 5; exec smb_prometheus_endpoint -a 0.0.0.0 -p %(ENV_DIB_SAMBA_METRICS_PORT)s /var/cache/samba/smbprofile.tdb; else echo 'Metrics disabled, exiting safely'; exit 0; fi"
user=root
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=9

[program:isc-stork-server]
command=/bin/bash -c "sleep 5 && exec /usr/bin/stork-server --use-env-file"
user=stork-server
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:isc-stork-agent]
command=/bin/bash -c "sleep 10 && exec /usr/bin/stork-agent --use-env-file"
user=stork-agent
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=11