[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
childlogdir=/var/log

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:chrony]
command=/usr/local/bin/dib-network-core-ctl run
user=root
environment=DIB_NETWORK_COMPONENT="chrony"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:samba]
command=/usr/local/bin/dib-identity-core-ctl run
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2

[program:bind]
command=/usr/local/bin/dib-network-core-ctl run
user=bind
environment=DIB_NETWORK_COMPONENT="bind"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=3

[program:cron]
command=/usr/sbin/cron -f -L 15
user=root
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=4

[program:postgresql]
command=/usr/local/bin/dib-db-ctl run
user=postgres
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

[program:init]
command=/usr/local/bin/dib-bootstrap-ctl
user=root
exitcodes=0
autorestart=false
startretries=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=6

[program:kea-dhcp4]
command=/usr/local/bin/dib-network-core-ctl run
user=_kea
environment=DIB_NETWORK_COMPONENT="kea-dhcp4"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=7

[program:kea-dhcp-ddns]
command=/usr/local/bin/dib-network-core-ctl run
user=_kea
environment=DIB_NETWORK_COMPONENT="kea-dhcp-ddns"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=8

[program:smb-prometheus-endpoint]
command=/usr/local/bin/dib-observability-ctl run
user=root
environment=DIB_OBSERVABILITY_COMPONENT="samba-metrics"
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=9

[program:isc-stork-server]
command=/usr/local/bin/dib-observability-ctl run
user=stork-server
environment=DIB_OBSERVABILITY_COMPONENT="stork-server"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:isc-stork-agent]
command=/usr/local/bin/dib-observability-ctl run
user=stork-agent
environment=DIB_OBSERVABILITY_COMPONENT="stork-agent"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=11