#!/bin/bash
set -e

# Start D-Bus daemon in the background (required for realm/AD operations)
echo "Starting D-Bus daemon..."
mkdir -p /var/run/dbus
dbus-daemon --system > /dev/null 2>&1 &
DBUS_PID=$!
sleep 1

# Start realmd daemon through D-Bus (required for realm join)
echo "Starting realmd daemon..."
mkdir -p /var/lib/realmd
/usr/libexec/realmd > /dev/null 2>&1 &
REALMD_PID=$!
sleep 1

# Start PackageKit service (needed for realmd)
echo "Starting PackageKit daemon..."
/usr/lib/packagekit/packagekitd > /dev/null 2>&1 &
PACKAGEKIT_PID=$!
sleep 1

# Start DHCP client on eth0 to get IP from DHCP server
echo "Starting DHCP client..."
dhclient -v eth0 > /dev/null 2>&1 &
DHCP_PID=$!
sleep 5

# Detect DHCP-assigned address and remove the non-DHCP primary address
DHCP_IP=$(ip -4 addr show eth0 | awk '/secondary.*dynamic/ {print $2}' | cut -d'/' -f1)
PRIMARY_IP=$(ip -4 addr show eth0 | awk '/inet / && !/secondary/ {print $2}' | cut -d'/' -f1)

if [[ -n "$DHCP_IP" && -n "$PRIMARY_IP" && "$DHCP_IP" != "$PRIMARY_IP" ]]; then
  echo "Removing non-DHCP primary address $PRIMARY_IP from eth0"
  ip addr del "$PRIMARY_IP/24" dev eth0 || true
  echo "Ensuring default route uses DHCP address $DHCP_IP"
  ip route replace default via 192.168.1.254 dev eth0 src "$DHCP_IP" || true
fi

# Fix DNS configuration for realm discovery
echo "Configuring DNS for realm discovery..."
cat > /etc/resolv.conf << 'RESOLV_EOF'
# Generated by entrypoint for realm/AD discovery
nameserver 192.168.1.1
search home.arpa
options timeout:5 attempts:3 rotate
RESOLV_EOF

# Configure Kerberos for domain authentication
echo "Configuring Kerberos for domain..."
cat > /etc/krb5.conf << 'KRB5_EOF'
[libdefaults]
    default_realm = HOME.ARPA
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    HOME.ARPA = {
        kdc = domain-server.home.arpa
        admin_server = domain-server.home.arpa
    }

[domain_realm]
    .home.arpa = HOME.ARPA
    home.arpa = HOME.ARPA
KRB5_EOF

# Start SSSD daemon (needed after realm join for user lookup)
echo "Starting SSSD daemon..."
/usr/sbin/sssd -D > /dev/null 2>&1 &
SSSD_PID=$!
sleep 5

echo "Container initialization complete"
echo "Network configuration:"
ip addr show eth0

# Check if a command was provided
if [ $# -gt 0 ]; then
  echo "Running command: $@"
  exec "$@"
else
  # Keep container running
  exec bash
fi
