#!/bin/bash
set -e

# Start D-Bus daemon in the background (required for realm/AD operations)
echo "Starting D-Bus daemon..."
mkdir -p /var/run/dbus
dbus-daemon --system > /dev/null 2>&1 &
sleep 1

# Start realmd daemon through D-Bus (required for realm join)
echo "Starting realmd daemon..."
mkdir -p /var/lib/realmd
/usr/libexec/realmd > /dev/null 2>&1 &
sleep 1

# Start PackageKit service (needed for realmd)
echo "Starting PackageKit daemon..."
/usr/lib/packagekit/packagekitd > /dev/null 2>&1 &
sleep 1

# Keep Docker-managed networking stable in CI. A DHCP lease request on the
# primary interface can race with Docker's own address assignment and briefly
# disconnect the test runner from the domain controller. Only attempt it when
# explicitly requested.
if [[ "${ENABLE_DHCP_CLIENT:-false}" == "true" ]]; then
  echo "Attempting DHCP lease on eth0 (non-fatal)..."
  if timeout 30 dhclient -1 -v eth0 > /dev/null 2>&1; then
    DHCP_IP=$(ip -4 addr show eth0 | awk '/dynamic/ {print $2}' | head -n1 | cut -d'/' -f1)
    if [[ -n "$DHCP_IP" ]]; then
      echo "DHCP lease acquired on eth0: $DHCP_IP"
    fi
  else
    echo "DHCP lease attempt did not complete; continuing with Docker-assigned networking"
  fi
else
  echo "Skipping DHCP lease request to keep Docker networking stable in CI"
fi

# Fix DNS configuration for realm discovery
echo "Configuring DNS for realm discovery..."
cat > /etc/resolv.conf << 'RESOLV_EOF'
# Generated by entrypoint for realm/AD discovery
nameserver 192.168.1.1
search home.arpa
options timeout:5 attempts:3 rotate
RESOLV_EOF

# Configure Kerberos for domain authentication
echo "Configuring Kerberos for domain..."
cat > /etc/krb5.conf << 'KRB5_EOF'
[libdefaults]
    default_realm = HOME.ARPA
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    HOME.ARPA = {
        kdc = domain-server.home.arpa
        admin_server = domain-server.home.arpa
    }

[domain_realm]
    .home.arpa = HOME.ARPA
    home.arpa = HOME.ARPA
KRB5_EOF

# Start SSSD daemon (needed after realm join for user lookup)
echo "Starting SSSD daemon..."
/usr/sbin/sssd -D > /dev/null 2>&1 &
sleep 5

wait_for_tcp_port() {
  local host="$1"
  local port="$2"
  local label="$3"

  for _ in $(seq 1 30); do
    if nc -z -w 1 "$host" "$port" > /dev/null 2>&1; then
      echo "$label reachable on $host:$port"
      return 0
    fi
    sleep 2
  done

  echo "Warning: timed out waiting for $label on $host:$port"
  return 1
}

DOMAIN_CONTROLLER_IP="${DOMAIN_CONTROLLER_IP:-192.168.1.1}"

echo "Container initialization complete"
echo "Network configuration:"
ip addr show eth0

echo "Waiting for domain controller reachability..."
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 389 "LDAP" || true
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 445 "SMB" || true
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 88 "Kerberos" || true
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 53 "DNS" || true

# Check if a command was provided
if [ $# -gt 0 ]; then
  echo "Running command: $*"
  exec "$@"
else
  # Keep container running
  exec bash
fi
