#!/bin/bash
set -e

# Start D-Bus daemon in the background (required for realm/AD operations)
echo "Starting D-Bus daemon..."
mkdir -p /var/run/dbus
dbus-daemon --system > /dev/null 2>&1 &
sleep 1

# Start realmd daemon through D-Bus (required for realm join)
echo "Starting realmd daemon..."
mkdir -p /var/lib/realmd
/usr/libexec/realmd > /dev/null 2>&1 &
sleep 1

# Start PackageKit service (needed for realmd)
echo "Starting PackageKit daemon..."
/usr/lib/packagekit/packagekitd > /dev/null 2>&1 &
sleep 1

DOMAIN_CONTROLLER_IP="${DOMAIN_CONTROLLER_IP:-192.168.1.1}"
SERVICE_INTERFACE=$(ip route get "$DOMAIN_CONTROLLER_IP" 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "dev") {print $(i+1); exit}}')
SERVICE_INTERFACE=${SERVICE_INTERFACE%%@*}
DIB_INTERFACE="${DIB_INTERFACE:-auto}"
if [[ -z "$DIB_INTERFACE" || "$DIB_INTERFACE" == "auto" ]]; then
  DIB_INTERFACE=$(ip -o link show | awk -F': ' -v service="$SERVICE_INTERFACE" '$2 !~ /^lo/ { iface=$2; sub(/@.*/, "", iface); if (iface != service) { print iface; exit } }')
  if [[ -z "$DIB_INTERFACE" ]]; then
    DIB_INTERFACE="$SERVICE_INTERFACE"
  fi
fi

export DIB_DHCP_TEST_INTERFACE="${DIB_INTERFACE:-}"
export DIB_DHCP_LEASE_FILE="/var/lib/dhcp/dhclient.leases"
export DIB_DHCP_LEASE_SUCCESS="false"

# Keep the default service path intact. Prefer a non-service interface for DHCP
# validation when one is available; otherwise renew on the service path itself.
echo "Service interface: ${SERVICE_INTERFACE:-unknown}"
echo "DHCP test interface: ${DIB_INTERFACE:-unavailable}"

if [[ "${ENABLE_DHCP_CLIENT:-false}" == "true" ]]; then
  if [[ -n "$DIB_INTERFACE" ]] && ip link show "$DIB_INTERFACE" > /dev/null 2>&1; then
    echo "Preparing DHCP test interface $DIB_INTERFACE..."
    ORIGINAL_DEFAULT_ROUTE=$(ip route show default | head -n1 || true)
    if [[ "$DIB_INTERFACE" != "$SERVICE_INTERFACE" ]]; then
      ip addr flush dev "$DIB_INTERFACE" scope global || true
    fi
    ip link set "$DIB_INTERFACE" up || true

    echo "Attempting DHCP lease on $DIB_INTERFACE..."
    if timeout 45 dhclient -4 -v -lf "$DIB_DHCP_LEASE_FILE" "$DIB_INTERFACE"; then
      export DIB_DHCP_LEASE_SUCCESS="true"
      DHCP_IP=$(ip -4 addr show "$DIB_INTERFACE" | awk '/inet / {print $2}' | head -n1 | cut -d'/' -f1)
      if [[ -n "$DHCP_IP" ]]; then
        echo "DHCP lease acquired on $DIB_INTERFACE: $DHCP_IP"
      fi
      if [[ "$DIB_INTERFACE" != "$SERVICE_INTERFACE" ]]; then
        ip route del default dev "$DIB_INTERFACE" 2>/dev/null || true
        if [[ -n "$ORIGINAL_DEFAULT_ROUTE" ]]; then
          ip route replace "$ORIGINAL_DEFAULT_ROUTE" || true
        fi
      fi
    else
      echo "DHCP lease attempt on $DIB_INTERFACE did not complete; continuing with current networking"
    fi
  else
    echo "DHCP interface $DIB_INTERFACE is not present; skipping DHCP lease attempt"
  fi
else
  echo "Skipping DHCP lease request to keep Docker networking stable in CI"
fi

# Fix DNS configuration for realm discovery
echo "Configuring DNS for realm discovery..."
DNS_SEARCH_DOMAIN="${DOMAIN_FQDN:-home.arpa}"
cat > /etc/resolv.conf <<RESOLV_EOF
# Generated by entrypoint for realm/AD discovery
nameserver ${DOMAIN_CONTROLLER_IP}
search ${DNS_SEARCH_DOMAIN}
options timeout:5 attempts:3 rotate
RESOLV_EOF

# Configure Kerberos for domain authentication
echo "Configuring Kerberos for domain..."
cat > /etc/krb5.conf << 'KRB5_EOF'
[libdefaults]
    default_realm = HOME.ARPA
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    HOME.ARPA = {
        kdc = domain-server.home.arpa
        admin_server = domain-server.home.arpa
    }

[domain_realm]
    .home.arpa = HOME.ARPA
    home.arpa = HOME.ARPA
KRB5_EOF

# Start SSSD daemon (needed after realm join for user lookup)
echo "Starting SSSD daemon..."
/usr/sbin/sssd -D > /dev/null 2>&1 &
sleep 5

wait_for_tcp_port() {
  local host="$1"
  local port="$2"
  local label="$3"

  for _ in $(seq 1 30); do
    if timeout 1 bash -c "</dev/tcp/${host}/${port}" > /dev/null 2>&1; then
      echo "$label reachable on $host:$port"
      return 0
    fi
    sleep 2
  done

  echo "Warning: timed out waiting for $label on $host:$port"
  return 1
}

echo "Container initialization complete"
echo "Network configuration:"
ip addr show

echo "Waiting for domain controller reachability..."
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 389 "LDAP" || true
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 636 "LDAPS" || true
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 445 "SMB" || true
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 88 "Kerberos" || true
wait_for_tcp_port "$DOMAIN_CONTROLLER_IP" 53 "DNS" || true

# Check if a command was provided
if [ $# -gt 0 ]; then
  echo "Running command: $*"
  exec "$@"
else
  # Keep container running
  exec bash
fi
